// Code generated by ogen, DO NOT EDIT.
package ogen

type GetCustomerByIDRes interface {
	getCustomerByIDRes()
}

type PostCreateCustomerRes interface {
	postCreateCustomerRes()
}

type PostSearchCustomerRes interface {
	postSearchCustomerRes()
}

type PutModifyCustomerByIDRes interface {
	putModifyCustomerByIDRes()
}
