// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/naoki.miyoshi/Data/pjct/en/en/backend/test/scripts/../../internal/port/driven/rdb/get_customer_by_id.go

// Package mock_rdbport is a generated GoMock package.
package mock_rdbport
