// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateNote implements createNote operation.
//
// メモを作成する.
//
// POST /notes
func (UnimplementedHandler) CreateNote(ctx context.Context, req *Note) (r *Note, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNoteByID implements getNoteByID operation.
//
// メモを取得する.
//
// GET /notes/{noteID}
func (UnimplementedHandler) GetNoteByID(ctx context.Context, params GetNoteByIDParams) (r GetNoteByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}
