// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/naoki344/go-pj-template/backend/internal/adapter/driven/rdb"
	"github.com/naoki344/go-pj-template/backend/internal/adapter/driver/ogen"
	"github.com/naoki344/go-pj-template/backend/internal/port/driven/rdb"
	"github.com/naoki344/go-pj-template/backend/internal/port/driver/api"
	"github.com/naoki344/go-pj-template/backend/internal/usecase/customer"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializeAPIService(db *rdbadapter.MySQL) *ogenadapter.APIAdapter {
	rdbPort := rdbport.NewRdbPort(db)
	customerUsecase := customerusecase.NewCustomerUsecase(rdbPort)
	customerAPIPort := apiport.NewCustomerAPIPort(customerUsecase)
	enAPIAdapter := ogenadapter.NewAPIAdapter(customerAPIPort)
	return enAPIAdapter
}
