openapi: 3.0.3
info:
  version: 1.0.0
  title: Note API
paths:
  /customers:
    post:
      summary: 顧客情報登録
      operationId: postCreateCustomer
      requestBody:
        $ref: "./components/requests/body/createCustomerRequest.yaml"
      responses:
        200:
          $ref: "./components/responses/createCustomerResponse.yaml"
        400:
          $ref: "./components/responses/errorClient.yaml"
        500:
          $ref: "./components/responses/errorServer.yaml"
  /customers/search:
    post:
      summary: 顧客情報検索
      operationId: postSearchCustomer
      requestBody:
        $ref: "./components/requests/body/searchCustomerRequest.yaml"
      responses:
        200:
          $ref: "./components/responses/searchCustomerResponse.yaml"
        400:
          $ref: "./components/responses/errorClient.yaml"
        404:
          $ref: "./components/responses/errorResourceNotFound.yaml"
        500:
          $ref: "./components/responses/errorServer.yaml"
  /customers/{customerID}:
    get:
      summary: 顧客情報参照
      operationId: getCustomerByID
      parameters:
        - $ref: "./components/requests/params/path/customerID.yaml"
      responses:
        200:
          $ref: "./components/responses/getCustomerByIDResponse.yaml"
        400:
          $ref: "./components/responses/errorClient.yaml"
        404:
          $ref: "./components/responses/errorResourceNotFound.yaml"
        500:
          $ref: "./components/responses/errorServer.yaml"
    put:
      summary: 顧客情報更新
      operationId: putModifyCustomerByID
      parameters:
        - $ref: "./components/requests/params/path/customerID.yaml"
      requestBody:
        $ref: "./components/requests/body/modifyCustomerRequest.yaml"
      responses:
        200:
          $ref: "./components/responses/modifyCustomerResponse.yaml"
        400:
          $ref: "./components/responses/errorClient.yaml"
        404:
          $ref: "./components/responses/errorResourceNotFound.yaml"
        500:
          $ref: "./components/responses/errorServer.yaml"
