// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"log/slog"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializeNoteService(cfg *Config, logger *slog.Logger) *noteService {
	sqlDb := NewDB(cfg, logger)
	getNoteByIDRepository := NewGetNoteByIDRepository(sqlDb)
	mainNoteService := NewNoteService(getNoteByIDRepository, logger)
	return mainNoteService
}
