// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"log/slog"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializeEnAPIService(cfg *Config, logger *slog.Logger) *enAPIService {
	sqlDb := NewDB(cfg, logger)
	getCustomerByIDRepository := NewGetCustomerByIDRepository(sqlDb)
	mainEnAPIService := NewEnAPIService(getCustomerByIDRepository, logger)
	return mainEnAPIService
}
