// Code generated by ogen, DO NOT EDIT.

package ogen

// Ref: #/components/schemas/address
type Address struct {
	// 郵便番号.
	PostalCode string `json:"postal_code"`
	// 都道府県ID.
	PrefID int64 `json:"pref_id"`
	// 市区町村.
	Address1 string `json:"address1"`
	// 番地・建物名・部屋.
	Address2 string `json:"address2"`
}

// GetPostalCode returns the value of PostalCode.
func (s *Address) GetPostalCode() string {
	return s.PostalCode
}

// GetPrefID returns the value of PrefID.
func (s *Address) GetPrefID() int64 {
	return s.PrefID
}

// GetAddress1 returns the value of Address1.
func (s *Address) GetAddress1() string {
	return s.Address1
}

// GetAddress2 returns the value of Address2.
func (s *Address) GetAddress2() string {
	return s.Address2
}

// SetPostalCode sets the value of PostalCode.
func (s *Address) SetPostalCode(val string) {
	s.PostalCode = val
}

// SetPrefID sets the value of PrefID.
func (s *Address) SetPrefID(val int64) {
	s.PrefID = val
}

// SetAddress1 sets the value of Address1.
func (s *Address) SetAddress1(val string) {
	s.Address1 = val
}

// SetAddress2 sets the value of Address2.
func (s *Address) SetAddress2(val string) {
	s.Address2 = val
}

// Ref: #/components/schemas/customer
type Customer struct {
	// 顧客ID.
	ID int64 `json:"id"`
	// 顧客名称.
	Name string `json:"name"`
	// 名称(カナ).
	NameKana OptString `json:"name_kana"`
	// 電話番号.
	Telephone string `json:"telephone"`
	// メールアドレス.
	Email string `json:"email"`
	// 担当者名.
	PersonInChargeName string `json:"person_in_charge_name"`
	// 担当者名(カナ).
	PersonInChargeNameKana OptString `json:"person_in_charge_name_kana"`
	Address                Address   `json:"address"`
}

// GetID returns the value of ID.
func (s *Customer) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *Customer) GetName() string {
	return s.Name
}

// GetNameKana returns the value of NameKana.
func (s *Customer) GetNameKana() OptString {
	return s.NameKana
}

// GetTelephone returns the value of Telephone.
func (s *Customer) GetTelephone() string {
	return s.Telephone
}

// GetEmail returns the value of Email.
func (s *Customer) GetEmail() string {
	return s.Email
}

// GetPersonInChargeName returns the value of PersonInChargeName.
func (s *Customer) GetPersonInChargeName() string {
	return s.PersonInChargeName
}

// GetPersonInChargeNameKana returns the value of PersonInChargeNameKana.
func (s *Customer) GetPersonInChargeNameKana() OptString {
	return s.PersonInChargeNameKana
}

// GetAddress returns the value of Address.
func (s *Customer) GetAddress() Address {
	return s.Address
}

// SetID sets the value of ID.
func (s *Customer) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Customer) SetName(val string) {
	s.Name = val
}

// SetNameKana sets the value of NameKana.
func (s *Customer) SetNameKana(val OptString) {
	s.NameKana = val
}

// SetTelephone sets the value of Telephone.
func (s *Customer) SetTelephone(val string) {
	s.Telephone = val
}

// SetEmail sets the value of Email.
func (s *Customer) SetEmail(val string) {
	s.Email = val
}

// SetPersonInChargeName sets the value of PersonInChargeName.
func (s *Customer) SetPersonInChargeName(val string) {
	s.PersonInChargeName = val
}

// SetPersonInChargeNameKana sets the value of PersonInChargeNameKana.
func (s *Customer) SetPersonInChargeNameKana(val OptString) {
	s.PersonInChargeNameKana = val
}

// SetAddress sets the value of Address.
func (s *Customer) SetAddress(val Address) {
	s.Address = val
}

// CustomerHeaders wraps Customer with response headers.
type CustomerHeaders struct {
	AccessControlAllowHeaders OptString
	AccessControlAllowMethods OptString
	AccessControlAllowOrigin  OptString
	Response                  Customer
}

// GetAccessControlAllowHeaders returns the value of AccessControlAllowHeaders.
func (s *CustomerHeaders) GetAccessControlAllowHeaders() OptString {
	return s.AccessControlAllowHeaders
}

// GetAccessControlAllowMethods returns the value of AccessControlAllowMethods.
func (s *CustomerHeaders) GetAccessControlAllowMethods() OptString {
	return s.AccessControlAllowMethods
}

// GetAccessControlAllowOrigin returns the value of AccessControlAllowOrigin.
func (s *CustomerHeaders) GetAccessControlAllowOrigin() OptString {
	return s.AccessControlAllowOrigin
}

// GetResponse returns the value of Response.
func (s *CustomerHeaders) GetResponse() Customer {
	return s.Response
}

// SetAccessControlAllowHeaders sets the value of AccessControlAllowHeaders.
func (s *CustomerHeaders) SetAccessControlAllowHeaders(val OptString) {
	s.AccessControlAllowHeaders = val
}

// SetAccessControlAllowMethods sets the value of AccessControlAllowMethods.
func (s *CustomerHeaders) SetAccessControlAllowMethods(val OptString) {
	s.AccessControlAllowMethods = val
}

// SetAccessControlAllowOrigin sets the value of AccessControlAllowOrigin.
func (s *CustomerHeaders) SetAccessControlAllowOrigin(val OptString) {
	s.AccessControlAllowOrigin = val
}

// SetResponse sets the value of Response.
func (s *CustomerHeaders) SetResponse(val Customer) {
	s.Response = val
}

func (*CustomerHeaders) getCustomerByIDRes()       {}
func (*CustomerHeaders) postCreateCustomerRes()    {}
func (*CustomerHeaders) putModifyCustomerByIDRes() {}

// Ref: #/components/schemas/errorModel
type ErrorModel struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}

// GetType returns the value of Type.
func (s *ErrorModel) GetType() string {
	return s.Type
}

// GetMessage returns the value of Message.
func (s *ErrorModel) GetMessage() string {
	return s.Message
}

// SetType sets the value of Type.
func (s *ErrorModel) SetType(val string) {
	s.Type = val
}

// SetMessage sets the value of Message.
func (s *ErrorModel) SetMessage(val string) {
	s.Message = val
}

// ErrorModelHeaders wraps ErrorModel with response headers.
type ErrorModelHeaders struct {
	AccessControlAllowHeaders OptString
	AccessControlAllowMethods OptString
	AccessControlAllowOrigin  OptString
	Response                  ErrorModel
}

// GetAccessControlAllowHeaders returns the value of AccessControlAllowHeaders.
func (s *ErrorModelHeaders) GetAccessControlAllowHeaders() OptString {
	return s.AccessControlAllowHeaders
}

// GetAccessControlAllowMethods returns the value of AccessControlAllowMethods.
func (s *ErrorModelHeaders) GetAccessControlAllowMethods() OptString {
	return s.AccessControlAllowMethods
}

// GetAccessControlAllowOrigin returns the value of AccessControlAllowOrigin.
func (s *ErrorModelHeaders) GetAccessControlAllowOrigin() OptString {
	return s.AccessControlAllowOrigin
}

// GetResponse returns the value of Response.
func (s *ErrorModelHeaders) GetResponse() ErrorModel {
	return s.Response
}

// SetAccessControlAllowHeaders sets the value of AccessControlAllowHeaders.
func (s *ErrorModelHeaders) SetAccessControlAllowHeaders(val OptString) {
	s.AccessControlAllowHeaders = val
}

// SetAccessControlAllowMethods sets the value of AccessControlAllowMethods.
func (s *ErrorModelHeaders) SetAccessControlAllowMethods(val OptString) {
	s.AccessControlAllowMethods = val
}

// SetAccessControlAllowOrigin sets the value of AccessControlAllowOrigin.
func (s *ErrorModelHeaders) SetAccessControlAllowOrigin(val OptString) {
	s.AccessControlAllowOrigin = val
}

// SetResponse sets the value of Response.
func (s *ErrorModelHeaders) SetResponse(val ErrorModel) {
	s.Response = val
}

type GetCustomerByIDBadRequest ErrorModelHeaders

func (*GetCustomerByIDBadRequest) getCustomerByIDRes() {}

type GetCustomerByIDInternalServerError ErrorModelHeaders

func (*GetCustomerByIDInternalServerError) getCustomerByIDRes() {}

type GetCustomerByIDNotFound ErrorModelHeaders

func (*GetCustomerByIDNotFound) getCustomerByIDRes() {}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/page
type Page struct {
	// ページサイズ.
	Size int64 `json:"size"`
	// 合計件数.
	Total int64 `json:"total"`
	// 現在のページ.
	Current int64 `json:"current"`
}

// GetSize returns the value of Size.
func (s *Page) GetSize() int64 {
	return s.Size
}

// GetTotal returns the value of Total.
func (s *Page) GetTotal() int64 {
	return s.Total
}

// GetCurrent returns the value of Current.
func (s *Page) GetCurrent() int64 {
	return s.Current
}

// SetSize sets the value of Size.
func (s *Page) SetSize(val int64) {
	s.Size = val
}

// SetTotal sets the value of Total.
func (s *Page) SetTotal(val int64) {
	s.Total = val
}

// SetCurrent sets the value of Current.
func (s *Page) SetCurrent(val int64) {
	s.Current = val
}

// Ref: #/components/schemas/pagination
type Pagination struct {
	// ページサイズ.
	Size int64 `json:"size"`
	// ページ番号.
	Number int64 `json:"number"`
}

// GetSize returns the value of Size.
func (s *Pagination) GetSize() int64 {
	return s.Size
}

// GetNumber returns the value of Number.
func (s *Pagination) GetNumber() int64 {
	return s.Number
}

// SetSize sets the value of Size.
func (s *Pagination) SetSize(val int64) {
	s.Size = val
}

// SetNumber sets the value of Number.
func (s *Pagination) SetNumber(val int64) {
	s.Number = val
}

type PostCreateCustomerBadRequest ErrorModelHeaders

func (*PostCreateCustomerBadRequest) postCreateCustomerRes() {}

type PostCreateCustomerInternalServerError ErrorModelHeaders

func (*PostCreateCustomerInternalServerError) postCreateCustomerRes() {}

// Ref: #/components/schemas/postCreateCustomer_request
type PostCreateCustomerRequest struct {
	// 顧客名称.
	Name string `json:"name"`
	// 名称(カナ).
	NameKana OptString `json:"name_kana"`
	// 電話番号.
	Telephone string `json:"telephone"`
	// メールアドレス.
	Email string `json:"email"`
	// 担当者名.
	PersonInChargeName string `json:"person_in_charge_name"`
	// 担当者名(カナ).
	PersonInChargeNameKana OptString `json:"person_in_charge_name_kana"`
	Address                Address   `json:"address"`
}

// GetName returns the value of Name.
func (s *PostCreateCustomerRequest) GetName() string {
	return s.Name
}

// GetNameKana returns the value of NameKana.
func (s *PostCreateCustomerRequest) GetNameKana() OptString {
	return s.NameKana
}

// GetTelephone returns the value of Telephone.
func (s *PostCreateCustomerRequest) GetTelephone() string {
	return s.Telephone
}

// GetEmail returns the value of Email.
func (s *PostCreateCustomerRequest) GetEmail() string {
	return s.Email
}

// GetPersonInChargeName returns the value of PersonInChargeName.
func (s *PostCreateCustomerRequest) GetPersonInChargeName() string {
	return s.PersonInChargeName
}

// GetPersonInChargeNameKana returns the value of PersonInChargeNameKana.
func (s *PostCreateCustomerRequest) GetPersonInChargeNameKana() OptString {
	return s.PersonInChargeNameKana
}

// GetAddress returns the value of Address.
func (s *PostCreateCustomerRequest) GetAddress() Address {
	return s.Address
}

// SetName sets the value of Name.
func (s *PostCreateCustomerRequest) SetName(val string) {
	s.Name = val
}

// SetNameKana sets the value of NameKana.
func (s *PostCreateCustomerRequest) SetNameKana(val OptString) {
	s.NameKana = val
}

// SetTelephone sets the value of Telephone.
func (s *PostCreateCustomerRequest) SetTelephone(val string) {
	s.Telephone = val
}

// SetEmail sets the value of Email.
func (s *PostCreateCustomerRequest) SetEmail(val string) {
	s.Email = val
}

// SetPersonInChargeName sets the value of PersonInChargeName.
func (s *PostCreateCustomerRequest) SetPersonInChargeName(val string) {
	s.PersonInChargeName = val
}

// SetPersonInChargeNameKana sets the value of PersonInChargeNameKana.
func (s *PostCreateCustomerRequest) SetPersonInChargeNameKana(val OptString) {
	s.PersonInChargeNameKana = val
}

// SetAddress sets the value of Address.
func (s *PostCreateCustomerRequest) SetAddress(val Address) {
	s.Address = val
}

// Ref: #/components/schemas/postSearchCustomer_200_response
type PostSearchCustomer200Response struct {
	// 検索結果.
	Customers []Customer `json:"customers"`
	Page      Page       `json:"page"`
}

// GetCustomers returns the value of Customers.
func (s *PostSearchCustomer200Response) GetCustomers() []Customer {
	return s.Customers
}

// GetPage returns the value of Page.
func (s *PostSearchCustomer200Response) GetPage() Page {
	return s.Page
}

// SetCustomers sets the value of Customers.
func (s *PostSearchCustomer200Response) SetCustomers(val []Customer) {
	s.Customers = val
}

// SetPage sets the value of Page.
func (s *PostSearchCustomer200Response) SetPage(val Page) {
	s.Page = val
}

// PostSearchCustomer200ResponseHeaders wraps PostSearchCustomer200Response with response headers.
type PostSearchCustomer200ResponseHeaders struct {
	AccessControlAllowHeaders OptString
	AccessControlAllowMethods OptString
	AccessControlAllowOrigin  OptString
	Response                  PostSearchCustomer200Response
}

// GetAccessControlAllowHeaders returns the value of AccessControlAllowHeaders.
func (s *PostSearchCustomer200ResponseHeaders) GetAccessControlAllowHeaders() OptString {
	return s.AccessControlAllowHeaders
}

// GetAccessControlAllowMethods returns the value of AccessControlAllowMethods.
func (s *PostSearchCustomer200ResponseHeaders) GetAccessControlAllowMethods() OptString {
	return s.AccessControlAllowMethods
}

// GetAccessControlAllowOrigin returns the value of AccessControlAllowOrigin.
func (s *PostSearchCustomer200ResponseHeaders) GetAccessControlAllowOrigin() OptString {
	return s.AccessControlAllowOrigin
}

// GetResponse returns the value of Response.
func (s *PostSearchCustomer200ResponseHeaders) GetResponse() PostSearchCustomer200Response {
	return s.Response
}

// SetAccessControlAllowHeaders sets the value of AccessControlAllowHeaders.
func (s *PostSearchCustomer200ResponseHeaders) SetAccessControlAllowHeaders(val OptString) {
	s.AccessControlAllowHeaders = val
}

// SetAccessControlAllowMethods sets the value of AccessControlAllowMethods.
func (s *PostSearchCustomer200ResponseHeaders) SetAccessControlAllowMethods(val OptString) {
	s.AccessControlAllowMethods = val
}

// SetAccessControlAllowOrigin sets the value of AccessControlAllowOrigin.
func (s *PostSearchCustomer200ResponseHeaders) SetAccessControlAllowOrigin(val OptString) {
	s.AccessControlAllowOrigin = val
}

// SetResponse sets the value of Response.
func (s *PostSearchCustomer200ResponseHeaders) SetResponse(val PostSearchCustomer200Response) {
	s.Response = val
}

func (*PostSearchCustomer200ResponseHeaders) postSearchCustomerRes() {}

type PostSearchCustomerBadRequest ErrorModelHeaders

func (*PostSearchCustomerBadRequest) postSearchCustomerRes() {}

type PostSearchCustomerInternalServerError ErrorModelHeaders

func (*PostSearchCustomerInternalServerError) postSearchCustomerRes() {}

type PostSearchCustomerNotFound ErrorModelHeaders

func (*PostSearchCustomerNotFound) postSearchCustomerRes() {}

// Ref: #/components/schemas/postSearchCustomer_request
type PostSearchCustomerRequest struct {
	Conditions PostSearchCustomerRequestConditions `json:"conditions"`
	Pagination Pagination                          `json:"pagination"`
}

// GetConditions returns the value of Conditions.
func (s *PostSearchCustomerRequest) GetConditions() PostSearchCustomerRequestConditions {
	return s.Conditions
}

// GetPagination returns the value of Pagination.
func (s *PostSearchCustomerRequest) GetPagination() Pagination {
	return s.Pagination
}

// SetConditions sets the value of Conditions.
func (s *PostSearchCustomerRequest) SetConditions(val PostSearchCustomerRequestConditions) {
	s.Conditions = val
}

// SetPagination sets the value of Pagination.
func (s *PostSearchCustomerRequest) SetPagination(val Pagination) {
	s.Pagination = val
}

// Ref: #/components/schemas/postSearchCustomer_request_conditions
type PostSearchCustomerRequestConditions struct {
	// 顧客名称.
	Name OptString `json:"name"`
}

// GetName returns the value of Name.
func (s *PostSearchCustomerRequestConditions) GetName() OptString {
	return s.Name
}

// SetName sets the value of Name.
func (s *PostSearchCustomerRequestConditions) SetName(val OptString) {
	s.Name = val
}

type PutModifyCustomerByIDBadRequest ErrorModelHeaders

func (*PutModifyCustomerByIDBadRequest) putModifyCustomerByIDRes() {}

type PutModifyCustomerByIDInternalServerError ErrorModelHeaders

func (*PutModifyCustomerByIDInternalServerError) putModifyCustomerByIDRes() {}

type PutModifyCustomerByIDNotFound ErrorModelHeaders

func (*PutModifyCustomerByIDNotFound) putModifyCustomerByIDRes() {}

// Ref: #/components/schemas/putModifyCustomerByID_request
type PutModifyCustomerByIDRequest struct {
	// 顧客ID.
	ID int64 `json:"id"`
	// 顧客名称.
	Name string `json:"name"`
	// 名称(カナ).
	NameKana OptString `json:"name_kana"`
	// 電話番号.
	Telephone string `json:"telephone"`
	// メールアドレス.
	Email string `json:"email"`
	// 担当者名.
	PersonInChargeName string `json:"person_in_charge_name"`
	// 担当者名(カナ).
	PersonInChargeNameKana OptString `json:"person_in_charge_name_kana"`
	Address                Address   `json:"address"`
}

// GetID returns the value of ID.
func (s *PutModifyCustomerByIDRequest) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *PutModifyCustomerByIDRequest) GetName() string {
	return s.Name
}

// GetNameKana returns the value of NameKana.
func (s *PutModifyCustomerByIDRequest) GetNameKana() OptString {
	return s.NameKana
}

// GetTelephone returns the value of Telephone.
func (s *PutModifyCustomerByIDRequest) GetTelephone() string {
	return s.Telephone
}

// GetEmail returns the value of Email.
func (s *PutModifyCustomerByIDRequest) GetEmail() string {
	return s.Email
}

// GetPersonInChargeName returns the value of PersonInChargeName.
func (s *PutModifyCustomerByIDRequest) GetPersonInChargeName() string {
	return s.PersonInChargeName
}

// GetPersonInChargeNameKana returns the value of PersonInChargeNameKana.
func (s *PutModifyCustomerByIDRequest) GetPersonInChargeNameKana() OptString {
	return s.PersonInChargeNameKana
}

// GetAddress returns the value of Address.
func (s *PutModifyCustomerByIDRequest) GetAddress() Address {
	return s.Address
}

// SetID sets the value of ID.
func (s *PutModifyCustomerByIDRequest) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *PutModifyCustomerByIDRequest) SetName(val string) {
	s.Name = val
}

// SetNameKana sets the value of NameKana.
func (s *PutModifyCustomerByIDRequest) SetNameKana(val OptString) {
	s.NameKana = val
}

// SetTelephone sets the value of Telephone.
func (s *PutModifyCustomerByIDRequest) SetTelephone(val string) {
	s.Telephone = val
}

// SetEmail sets the value of Email.
func (s *PutModifyCustomerByIDRequest) SetEmail(val string) {
	s.Email = val
}

// SetPersonInChargeName sets the value of PersonInChargeName.
func (s *PutModifyCustomerByIDRequest) SetPersonInChargeName(val string) {
	s.PersonInChargeName = val
}

// SetPersonInChargeNameKana sets the value of PersonInChargeNameKana.
func (s *PutModifyCustomerByIDRequest) SetPersonInChargeNameKana(val OptString) {
	s.PersonInChargeNameKana = val
}

// SetAddress sets the value of Address.
func (s *PutModifyCustomerByIDRequest) SetAddress(val Address) {
	s.Address = val
}
