// Code generated by ogen, DO NOT EDIT.

package ogen

type GetCustomerByIDInternalServerError struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}

// GetType returns the value of Type.
func (s *GetCustomerByIDInternalServerError) GetType() string {
	return s.Type
}

// GetMessage returns the value of Message.
func (s *GetCustomerByIDInternalServerError) GetMessage() string {
	return s.Message
}

// SetType sets the value of Type.
func (s *GetCustomerByIDInternalServerError) SetType(val string) {
	s.Type = val
}

// SetMessage sets the value of Message.
func (s *GetCustomerByIDInternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*GetCustomerByIDInternalServerError) getCustomerByIDRes() {}

type GetCustomerByIDNotFound struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}

// GetType returns the value of Type.
func (s *GetCustomerByIDNotFound) GetType() string {
	return s.Type
}

// GetMessage returns the value of Message.
func (s *GetCustomerByIDNotFound) GetMessage() string {
	return s.Message
}

// SetType sets the value of Type.
func (s *GetCustomerByIDNotFound) SetType(val string) {
	s.Type = val
}

// SetMessage sets the value of Message.
func (s *GetCustomerByIDNotFound) SetMessage(val string) {
	s.Message = val
}

func (*GetCustomerByIDNotFound) getCustomerByIDRes() {}

type GetCustomerByIDOK struct {
	ID      int64  `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

// GetID returns the value of ID.
func (s *GetCustomerByIDOK) GetID() int64 {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *GetCustomerByIDOK) GetTitle() string {
	return s.Title
}

// GetContent returns the value of Content.
func (s *GetCustomerByIDOK) GetContent() string {
	return s.Content
}

// SetID sets the value of ID.
func (s *GetCustomerByIDOK) SetID(val int64) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *GetCustomerByIDOK) SetTitle(val string) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *GetCustomerByIDOK) SetContent(val string) {
	s.Content = val
}

func (*GetCustomerByIDOK) getCustomerByIDRes() {}

type PostCreateCustomerOK struct {
	ID      int64  `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

// GetID returns the value of ID.
func (s *PostCreateCustomerOK) GetID() int64 {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *PostCreateCustomerOK) GetTitle() string {
	return s.Title
}

// GetContent returns the value of Content.
func (s *PostCreateCustomerOK) GetContent() string {
	return s.Content
}

// SetID sets the value of ID.
func (s *PostCreateCustomerOK) SetID(val int64) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *PostCreateCustomerOK) SetTitle(val string) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *PostCreateCustomerOK) SetContent(val string) {
	s.Content = val
}

type PostCreateCustomerReq struct {
	ID      int64  `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

// GetID returns the value of ID.
func (s *PostCreateCustomerReq) GetID() int64 {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *PostCreateCustomerReq) GetTitle() string {
	return s.Title
}

// GetContent returns the value of Content.
func (s *PostCreateCustomerReq) GetContent() string {
	return s.Content
}

// SetID sets the value of ID.
func (s *PostCreateCustomerReq) SetID(val int64) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *PostCreateCustomerReq) SetTitle(val string) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *PostCreateCustomerReq) SetContent(val string) {
	s.Content = val
}
