// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetCustomerByID implements getCustomerByID operation.
	//
	// 顧客情報参照.
	//
	// GET /customers/{customerID}
	GetCustomerByID(ctx context.Context, params GetCustomerByIDParams) (GetCustomerByIDRes, error)
	// PostCreateCustomer implements postCreateCustomer operation.
	//
	// 顧客情報登録.
	//
	// POST /customers
	PostCreateCustomer(ctx context.Context, req *PostCreateCustomerReq) (PostCreateCustomerRes, error)
	// PostSearchCustomer implements postSearchCustomer operation.
	//
	// 顧客情報検索.
	//
	// POST /customers/search
	PostSearchCustomer(ctx context.Context, req *PostSearchCustomerReq) (PostSearchCustomerRes, error)
	// PutModifyCustomerByID implements putModifyCustomerByID operation.
	//
	// 顧客情報更新.
	//
	// PUT /customers/{customerID}
	PutModifyCustomerByID(ctx context.Context, req *PutModifyCustomerByIDReq, params PutModifyCustomerByIDParams) (PutModifyCustomerByIDRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
