// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetCustomerByID implements getCustomerByID operation.
//
// 顧客を取得する.
//
// GET /customers/{customerID}
func (UnimplementedHandler) GetCustomerByID(ctx context.Context, params GetCustomerByIDParams) (r *GetCustomerByIDOK, _ error) {
	return r, ht.ErrNotImplemented
}

// PostCreateCustomer implements postCreateCustomer operation.
//
// 顧客を登録する.
//
// POST /customers
func (UnimplementedHandler) PostCreateCustomer(ctx context.Context, req *PostCreateCustomerReq) (r *PostCreateCustomerOK, _ error) {
	return r, ht.ErrNotImplemented
}
