// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetCustomerByID implements getCustomerByID operation.
	//
	// 顧客を取得する.
	//
	// GET /customers/{customerID}
	GetCustomerByID(ctx context.Context, params GetCustomerByIDParams) (*GetCustomerByIDOK, error)
	// PostCreateCustomer implements postCreateCustomer operation.
	//
	// 顧客を登録する.
	//
	// POST /customers
	PostCreateCustomer(ctx context.Context, req *PostCreateCustomerReq) (*PostCreateCustomerOK, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
