// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetCustomerByID implements getCustomerByID operation.
//
// 顧客情報参照.
//
// GET /customers/{customerID}
func (UnimplementedHandler) GetCustomerByID(ctx context.Context, params GetCustomerByIDParams) (r GetCustomerByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostCreateCustomer implements postCreateCustomer operation.
//
// 顧客情報登録.
//
// POST /customers
func (UnimplementedHandler) PostCreateCustomer(ctx context.Context, req *PostCreateCustomerReq) (r PostCreateCustomerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostSearchCustomer implements postSearchCustomer operation.
//
// 顧客情報検索.
//
// POST /customers/search
func (UnimplementedHandler) PostSearchCustomer(ctx context.Context, req *PostSearchCustomerReq) (r PostSearchCustomerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutModifyCustomerByID implements putModifyCustomerByID operation.
//
// 顧客情報更新.
//
// PUT /customers/{customerID}
func (UnimplementedHandler) PutModifyCustomerByID(ctx context.Context, req *PutModifyCustomerByIDReq, params PutModifyCustomerByIDParams) (r PutModifyCustomerByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}
