name: golangci-lint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'backend/go.mod'
      - run: go version
      - name: go mod tidy
        run: |
          cd backend
          go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: backend
